server:
  service:
    type: LoadBalancer
    port: 9090
  extraScrapeConfigs: |
    - job_name: 'azuredev-appservice'
      metrics_path: /metrics
      static_configs:
        - targets: ['azuredev-appservice.dev.svc.cluster.local:8080']